In [1]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
print(os.listdir("../input"))
import gc

['merchants.csv', 'Data_Dictionary.xlsx', 'historical_transactions.csv', 'new_merchant_transactions.csv', 'sample_submission.csv', 'test.csv', 'train.csv']

In [2]:
train = pd.read_csv('../input/train.csv')
test = pd.read_csv('../input/test.csv')

In [3]:
def add_historical_features(df):
    his_tran = pd.read_csv('../input/historical_transactions.csv')
    his_tran['authorized_flag'] = his_tran['authorized_flag'].apply(lambda x: 1 if x == 'Y' else 0)
    t_df = pd.merge(df,pd.DataFrame(his_tran.groupby(['card_id']).count()['purchase_amount']),on='card_id',how='left')
    t_df = t_df.rename({'purchase_amount':'purchase_count'}, axis='columns')
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).sum()['installments']),on='card_id',how='left',suffixes=('a','b'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).mean()['installments']),on='card_id',how='left',suffixes=('c','d'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).std()['installments']),on='card_id',how='left',suffixes=('e','f'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','authorized_flag']).count()['purchase_amount'].unstack()),on='card_id',how='left',suffixes=('g','h'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','authorized_flag']).mean()['purchase_amount'].unstack()),on='card_id',how='left',suffixes=('i','j'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','authorized_flag']).std()['purchase_amount'].unstack()),on='card_id',how='left',suffixes=('k','l'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).count()['city_id']),on='card_id',how='left')
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).sum()['purchase_amount']),on='card_id',how='left',suffixes=('m','n'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).mean()['purchase_amount']),on='card_id',how='left',suffixes=('o','p'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).std()['purchase_amount']),on='card_id',how='left',suffixes=('q','r'))
    his_tran['category_1'] = his_tran['category_1'].astype('category')
    his_tran['category_1'] = his_tran['category_1'].cat.codes
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_1']].groupby(['card_id']).max()),on='card_id',how='left',suffixes=('s','t'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_1']].groupby(['card_id']).min()),on='card_id',how='left',suffixes=('u','v'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_1']).count()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('w','x'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_1']).mean()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('y','z'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_1']).std()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_a','_b'))
    his_tran['category_2'] = his_tran['category_2'].astype('category')
    his_tran['category_2'] = his_tran['category_2'].cat.codes
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_2']].groupby(['card_id']).max()),on='card_id',how='left',suffixes=('_c','_d'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_2']].groupby(['card_id']).min()),on='card_id',how='left',suffixes=('_e','_f'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_2']).count()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_g','_h'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_2']).mean()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_i','_j'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_2']).std()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_k','_l'))
    his_tran['category_3'] = his_tran['category_3'].astype('category')
    his_tran['category_3'] = his_tran['category_3'].cat.codes
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_3']].groupby(['card_id']).max()),on='card_id',how='left',suffixes=('_m','_n'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran[['card_id','category_3']].groupby(['card_id']).min()),on='card_id',how='left',suffixes=('_o','_p'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_3']).count()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_q','_r'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_3']).mean()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_s','_t'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','category_3']).std()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_u','_v'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).sum()['month_lag']),on='card_id',how='left',suffixes=('_w','_x'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).mean()['month_lag']),on='card_id',how='left',suffixes=('_y','_z'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id']).std()['month_lag']),on='card_id',how='left',suffixes=('_a1','_b1'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','month_lag']).count()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_a2','_b2'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','month_lag']).mean()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_a3','_b3'))
    t_df = pd.merge(t_df,pd.DataFrame(his_tran.groupby(['card_id','month_lag']).std()['authorized_flag'].unstack()),on='card_id',how='left',suffixes=('_a4','_b4'))
    return t_df

In [4]:
train_df = add_historical_features(train)
train_df.head()

  first_active_month          card_id    ...           -1         0
0            2017-06  C_ID_92a2005557    ...     0.000000  0.000000
1            2017-01  C_ID_3d0044924f    ...     0.204030  0.000000
2            2016-08  C_ID_d639edf6cd    ...     0.000000       NaN
3            2017-09  C_ID_186d6a6901    ...     0.000000  0.000000
4            2017-11  C_ID_cdbd2c0db2    ...     0.206185  0.284029

[5 rows x 107 columns]

In [5]:
train_df.fillna(0,inplace=True)

In [6]:
test_df = add_historical_features(test)
test_df.head()

  first_active_month          card_id    ...          -1         0
0            2017-04  C_ID_0ab67a22ab    ...     0.57735  0.316228
1            2017-01  C_ID_130fd0cbdd    ...         NaN  0.000000
2            2017-08  C_ID_b709037bc5    ...     0.00000  0.577350
3            2017-12  C_ID_d27d835a9f    ...     0.00000  0.000000
4            2015-12  C_ID_2b5e3df5c2    ...     0.50000  0.000000

[5 rows x 106 columns]

In [7]:
test_df.fillna(0,inplace=True)

In [8]:
features = train_df.columns.drop(['first_active_month','card_id','target']).values

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_df[features], train_df['target'], test_size = 0.25, random_state = 0)

In [10]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

In [11]:
d_train = lgb.Dataset(x_train, label=y_train)

In [12]:
params = {}
params['learning_rate'] = 0.005
params['boosting_type'] = 'gbdt'
params['objective'] = 'regression'
#params['bagging_fraction'] = 0.7
#params['bagging_freq'] = 100
params['metric'] = 'rmse'
params['sub_feature'] = 0.78
params['num_leaves'] = 87
params['min_data'] = 488
params['max_depth'] = 33

In [13]:
clf = lgb.train(params, d_train, 2000)

In [14]:
y_pred = clf.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
print(mse**0.5)

3.8053519500198254

In [15]:
y_pred2 = clf.predict(x_train)
mse2 = mean_squared_error(y_train,y_pred2)
print(mse2**0.5)

3.614074045118126

In [16]:
test_df['target'] = clf.predict(test_df[features])

In [17]:
test_df[['card_id','target']].to_csv('sub_dash.csv',index=False)